name: Deploy React App
on:
  push:
    branches: 
      - 'master'
    # paths-ignore: 
    #   - '.github/workflows/*'
jobs:
  test-my-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache packages
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint-my-app: 
    runs-on: ubuntu-latest
    needs: test-my-app
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache packages
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json')}} 
      - name: Install Dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build-my-app: 
    needs: lint-my-app
    continue-on-error: true
    strategy: 
      matrix:
        my-node-ver: [14, 16]
        my-os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.my-os}}
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install nodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: ${{matrix.my-node-ver}}
      - name: Cache packages
        uses: actions/cache@v4
        with: 
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deployment...
