name: Test React App
on: push
jobs:
  test-my-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test application
        run: npm run test

