name: Deploy React App
on: push
jobs:
  test-my-app:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint-my-app: 
    runs-on: ubuntu-latest
    needs: test-my-app
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build-my-app: 
    needs: lint-my-app
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deployment...
